name: Eight Workflow
on: workflow_dispatch
  # push: 
  #   branches:
  #   - main
  #   - dev
env:
  MONGO_DB_NAME: ${{secrets.MONGO_DB_NAME}}
jobs:
  test:
    environment: test
    env:
      MONGODB_CLUSTER_ADDRESS: ${{secrets.MONGODB_CLUSTER_ADDRESS}}
      MONGODB_USERNAME: ${{secrets.MONGODB_USERNAME}}
      MONGODB_PASSWORD: ${{secrets.MONGODB_PASSWORD}}
      PORT: ${{secrets.PORT}}
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v3
      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-node-modules-${{hashFiles('**/package-lock.json')}}
      
      - name: Install Dependency
        working-directory: 5. Environment Variables And Secret/starting-project
        run: npm ci
      - name: Run Server
        working-directory: 5. Environment Variables And Secret/starting-project
        run: npm start & npx wait-on http://127.0.0.1:$PORT
      - name: Test
        working-directory: 5. Environment Variables And Secret/starting-project
        run: npm run test
      - name: Echo
        run: echo "${{env.MONGODB_USERNAME}}"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Echo 1
        run: echo "${{env.MONGODB_USERNAME}}"
      - name: Echo 2
        run: echo "${{env.MONGO_DB_NAME}}"