name: Eleven Workflow
on:
  push:
    branches:
      - main

jobs:
    build:
      strategy:
        matrix: 
          node-version: [11,12,13]
          os: [ubuntu-latest, windows-latest]
      runs-on: ${{matrix.os}}
      steps:
        - name: Get Code
          uses: actions/checkout@v3
        - name: Install Node
          uses: actions/setup-node@v3
          with:
            node-version: ${{matrix.node-version}}
        - name: Install Dependencies
          working-directory: 6. Controlling Workflow And Jobs/starting-project
          run: npm ci
        - name: TestCode
          working-directory: 6. Controlling Workflow And Jobs/starting-project
          run: npm run build