name: Fifth Workflow
on:
  issues:
    types: [opened]
jobs:
  issue: 
    runs-on: ubuntu-latest
    steps:
    - name: "Issue was created"
      run: echo "Issue was created ${{toJSON(github.event)}}"
