name: Deployment With Docker
on: 
  push:
    branches:
      - main
      - dev
env:
  MONGODB_DB_NAME: gha_demo
jobs:
  test:
    environment: test
    runs-on: ubuntu-latest
    container: node:18
    env: 
      MONGODB_CONNECTION_PROTOCOL: mongodb
      MONGODB_CLUSTER_ADDRESS: mongodb
      MONGODB_USERNAME: root 
      MONGODB_PASSWORD: example
      PORT: 8080
    services:
      mongodb: 
        image: mongo:latest
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Cache Dependenies
        id: cache
        uses: actions/cache@v4
        with:
          path: 7-jobs-and-docker-container/starting-project/node_modules
          key: node-modules-${{hashFiles('7-jobs-and-docker-container/starting-project/package-lock.json')}}
      - name: Install Dependencies
        working-directory: 7-jobs-and-docker-container/starting-project
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Run Server
        working-directory: 7-jobs-and-docker-container/starting-project
        run: npm start & npx wait-on http://127.0.0.1:$PORT
      - name: Run Test
        working-directory: 7-jobs-and-docker-container/starting-project
        run: npm test