name: Nine Workflow
on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Cache Dependenies
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          working-directory: 6. Controlling Workflow And Jobs/starting-project
          key: node-modules-${{hashFiles('**/package-lock.json')}}
      - name: Install Dependencies
        run: npm ci
      - name: Lint Code
        run: npm run lint
        
  test:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Cache Dependenies
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          working-directory: 6. Controlling Workflow And Jobs/starting-project
          key: node-modules-${{hashFiles('**/package-lock.json')}}
      - name: Install Dependencies
        run: npm ci
      - name: TestCode
        run: npm run test
      - name: Upload Test Report
        uses: actions/upload-artifact
        with:
          name: test-report
          path: test.json

  build:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Cache Dependenies
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          working-directory: 6. Controlling Workflow And Jobs/starting-project
          key: node-modules-${{hashFiles('**/package-lock.json')}}
      - name: Install Dependencies
        run: npm ci
      - name: TestCode
        run: npm run build
      - name: Upload Build Results
        uses: actions/upload-artifact
        with:
          name: dist-result
          path: dist

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Get Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist-result
      - name: Output Contents
        run: ls
      - name: Deploy
        run: echo "Deploying"
