name: Test Workflow
on: workflow_dispatch
jobs: 
  first-job: 
    runs-on: ubuntu-latest
    steps:
      - name: Get Repository
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with: 
          node-version: 18  
      - name: LS
        run: ls -a
      # - name: Install Dependency
      #   uses: npm ci
      # - name: Run Test
      #   uses: npm test