name: Deploy Website
on: workflow_dispatch
  # push:
  #   branches:
  #     - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-node-modules-${{hashFiles('**/package-lock.json')}}
      - name: Install Dependency
        working-directory: 4. Job Artifacts And Output/starting-project
        run: npm ci
      - name: Test Code
        working-directory: 4. Job Artifacts And Output/starting-project
        run: npm run test
  build:
    needs: [test]
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{steps.publish.outputs.script-file}}
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-node-modules-${{hashFiles('**/package-lock.json')}}
      - name: Install Dependency
        working-directory: 4. Job Artifacts And Output/starting-project
        run: npm ci
      - name: Test Code
        working-directory: 4. Job Artifacts And Output/starting-project
        run: npm run build
      
      - name: Publish Javascript File Name
        id: publish
        working-directory: 4. Job Artifacts And Output/starting-project
        run: find dist/assets/*js -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT ';'
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with: 
          name: dist-files
          path: |
            4. Job Artifacts And Output/starting-project/dist
  deploy:
    needs: [test, build]
    runs-on: ubuntu-latest
    steps:
      - name: Get Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
      - name: Output File Name
        run: echo "${{needs.build.outputs.script-file}}"
      - name: ls
        run: ls -a
          