name: Reusable Workflow
on: 
  workflow_call:
    inputs:
      file_name: 
        description: file_name
        default: dist
        type: string
    outputs:
      return_name:
        description: return name
        value: ${{jobs.info.outputs.outcome}}
jobs: 
  info:
    outputs:
      outcome: ${{steps.step-result.outputs.return_name}}
    runs-on: ubuntu-latest
    steps:
      - name: Echoing
        uses: actions/download-artifact@v4
        with:
          name: ${{inputs.file_name}}
      - name: echo
        run: ls -a
      - name: result output
        id: step-result
        run: echo "return_name=success" >> "$GITHUB_OUTPUT"